### ISSUE TITLE
Searching for songs should show when it was last played or last requested

### ISSUE THREAD

**Issue by CrimsonVoid** [R-a-dio/Hanyuu-sama#7]
I'm not sure if I'm the only one that does this but I like to check when a song I'm requesting was last played or requested and if it's been played in the last 24 hours I won't request it regardless of cooldown time. It might be nice to have the last played and requested times for songs so that someone can easily see when it was last played. I know that Hanyuu pretty much takes care of this already, so if it's understandable if it's a redundant feature.

**Comment by Wessie** [comment]
We should test how big the returned string is when we add last played and last requested times to search results. I'm thinking it is too big and we should split it into two messages. 

Not sure if we can be happy with search returning two messages instead of one.

**Comment by Wessie** [comment]
Suggested format: `"{metadata:s} ({song_id:d})(LP: {lp:s})(R: {requested:s})"`

`metadata`: self explanatory

`song_id` is the same as now, the song id in the database

`lp`: Time since last played in humanized format. So a last played of 2 days 7 hours and 30 minutes ago would be "2d7h" stripping the minutes.

`request`: Same as last played but then for last request.

Example output: `AiRI - Dreamer (4469)(LP: 2d5h)(R: 2d6h)`
